# Generated by Django 4.2.4 on 2023-08-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
