# Generated by Django 4.2.4 on 2023-09-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='blog.comment'),
            preserve_default=False,
        ),
    ]
