# Generated by Django 3.2.12 on 2023-09-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='future_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/future_image'),
        ),
    ]
