# Generated by Django 4.2.4 on 2023-08-24 05:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='question_text', unique=True),
            preserve_default=False,
        ),
    ]
